name: Playwright Tests
on:
  push:
    branches: [ main, master]
  pull_request:
    branches: [main, master]
  jobs:
    test:
    timeout-minutes: 60
    runs-on: ubuntu_latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt