import time,pytest
from playwright.sync_api import Playwright, sync_playwright, expect
def test_script():
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(executable_path="C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe", headless=False, args=["--disable-incognito", "--start-maximized"])
        context = browser.new_context(no_viewport=True)
        #browser.new_context(no_viewport=True)
        #context.set_viewport_size(width=1920, height=1080)
        page = context.new_page()
        #page.goto("https://kindstaging.azure.dynamicdemand.ai/promo/category-diagnostics/growth-analysis")
        page.goto("https://kindstaging.azure.dynamicdemand.ai/")
        #page.evaluate("() => { window.maximize() }")
        page.get_by_placeholder("Enter your Email ID").click()
        page.get_by_placeholder("Enter your Email ID").fill("raviranjan.singh@asper.ai")
        page.get_by_placeholder("Enter your Password").click()
        page.get_by_placeholder("Enter your Password").fill("Mumbai#1234$")
        page.wait_for_timeout(5000)
        page.get_by_role("button", name="LOGIN").click()
        # page.goto("https://kindstaging.azure.dynamicdemand.ai/implicit/callback?code=ZeYlrtkMjTmRjbxrcNb6T3XS8dc2KY89yqTPQ7vdKrY&state=tpSjZz017kz7XLMaV5QOCl8SiLEKLQGuA4iUyw8WPeD4BXYEV2fVAdWwNnMxasRX")
        page.goto("https://kindstaging.azure.dynamicdemand.ai/promo/category-diagnostics/growth-analysis")
        time.sleep(8000)
        expect(page.get_by_text("Category Diagnostics")).to_be_visible()
        expect(page.get_by_text("Pricing Analytics")).to_be_visible()
        expect(page.get_by_text("Promo Analytics")).to_be_visible()
        expect(page.get_by_text("Price & Promo Modeling")).to_be_visible()
        expect(page.get_by_role("link", name="User Manual")).to_be_visible()
        page.get_by_text("RS", exact=True).click()
        page.get_by_text("Logout").click()
        # ---------------------
        context.close()
        browser.close()
